// Mocks generated by Mockito 5.4.5 from annotations
// in openvine/test/services/upload_manager_robust_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:openvine/services/direct_upload_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDirectUploadResult_0 extends _i1.SmartFake
    implements _i2.DirectUploadResult {
  _FakeDirectUploadResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DirectUploadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDirectUploadService extends _i1.Mock
    implements _i2.DirectUploadService {
  MockDirectUploadService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<String> get activeUploads => (super.noSuchMethod(
        Invocation.getter(#activeUploads),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i3.Future<_i2.DirectUploadResult> uploadVideo({
    required _i4.File? videoFile,
    required String? nostrPubkey,
    String? title,
    String? description,
    List<String>? hashtags,
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadVideo,
          [],
          {
            #videoFile: videoFile,
            #nostrPubkey: nostrPubkey,
            #title: title,
            #description: description,
            #hashtags: hashtags,
            #onProgress: onProgress,
          },
        ),
        returnValue:
            _i3.Future<_i2.DirectUploadResult>.value(_FakeDirectUploadResult_0(
          this,
          Invocation.method(
            #uploadVideo,
            [],
            {
              #videoFile: videoFile,
              #nostrPubkey: nostrPubkey,
              #title: title,
              #description: description,
              #hashtags: hashtags,
              #onProgress: onProgress,
            },
          ),
        )),
      ) as _i3.Future<_i2.DirectUploadResult>);

  @override
  _i3.Future<void> cancelUpload(String? videoId) => (super.noSuchMethod(
        Invocation.method(
          #cancelUpload,
          [videoId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<double>? getProgressStream(String? videoId) =>
      (super.noSuchMethod(Invocation.method(
        #getProgressStream,
        [videoId],
      )) as _i3.Stream<double>?);

  @override
  bool isUploading(String? videoId) => (super.noSuchMethod(
        Invocation.method(
          #isUploading,
          [videoId],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<_i2.DirectUploadResult> uploadProfilePicture({
    required _i4.File? imageFile,
    required String? nostrPubkey,
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadProfilePicture,
          [],
          {
            #imageFile: imageFile,
            #nostrPubkey: nostrPubkey,
            #onProgress: onProgress,
          },
        ),
        returnValue:
            _i3.Future<_i2.DirectUploadResult>.value(_FakeDirectUploadResult_0(
          this,
          Invocation.method(
            #uploadProfilePicture,
            [],
            {
              #imageFile: imageFile,
              #nostrPubkey: nostrPubkey,
              #onProgress: onProgress,
            },
          ),
        )),
      ) as _i3.Future<_i2.DirectUploadResult>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
