// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/services/vine_recording_controller_macos_refactor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter/foundation.dart' as _i3;
import 'package:flutter/material.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:openvine/services/vine_recording_controller.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWidget_0 extends _i1.SmartFake implements _i2.Widget {
  _FakeWidget_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [MacOSCameraInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockMacOSCameraInterface extends _i1.Mock
    implements _i4.MacOSCameraInterface {
  MockMacOSCameraInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isRecording =>
      (super.noSuchMethod(Invocation.getter(#isRecording), returnValue: false)
          as bool);

  @override
  bool get isSingleRecordingMode =>
      (super.noSuchMethod(
            Invocation.getter(#isSingleRecordingMode),
            returnValue: false,
          )
          as bool);

  @override
  _i2.Widget get previewWidget =>
      (super.noSuchMethod(
            Invocation.getter(#previewWidget),
            returnValue: _FakeWidget_0(this, Invocation.getter(#previewWidget)),
          )
          as _i2.Widget);

  @override
  bool get canSwitchCamera =>
      (super.noSuchMethod(
            Invocation.getter(#canSwitchCamera),
            returnValue: false,
          )
          as bool);

  @override
  set currentRecordingPath(String? _currentRecordingPath) => super.noSuchMethod(
    Invocation.setter(#currentRecordingPath, _currentRecordingPath),
    returnValueForMissingStub: null,
  );

  @override
  set isRecording(bool? _isRecording) => super.noSuchMethod(
    Invocation.setter(#isRecording, _isRecording),
    returnValueForMissingStub: null,
  );

  @override
  set isSingleRecordingMode(bool? _isSingleRecordingMode) => super.noSuchMethod(
    Invocation.setter(#isSingleRecordingMode, _isSingleRecordingMode),
    returnValueForMissingStub: null,
  );

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i5.Future<void> get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> startRecordingSegment(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#startRecordingSegment, [filePath]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> stopRecordingSegment() =>
      (super.noSuchMethod(
            Invocation.method(#stopRecordingSegment, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> completeRecording() =>
      (super.noSuchMethod(
            Invocation.method(#completeRecording, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> stopSingleRecording() =>
      (super.noSuchMethod(
            Invocation.method(#stopSingleRecording, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String> waitForRecordingCompletion({
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#waitForRecordingCompletion, [], {
              #timeout: timeout,
            }),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#waitForRecordingCompletion, [], {
                  #timeout: timeout,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  List<_i4.RecordingSegment> getVirtualSegments() =>
      (super.noSuchMethod(
            Invocation.method(#getVirtualSegments, []),
            returnValue: <_i4.RecordingSegment>[],
          )
          as List<_i4.RecordingSegment>);

  @override
  _i5.Future<void> switchCamera() =>
      (super.noSuchMethod(
            Invocation.method(#switchCamera, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );

  @override
  void startInitialization() => super.noSuchMethod(
    Invocation.method(#startInitialization, []),
    returnValueForMissingStub: null,
  );

  @override
  void completeInitialization() => super.noSuchMethod(
    Invocation.method(#completeInitialization, []),
    returnValueForMissingStub: null,
  );

  @override
  void failInitialization(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#failInitialization, [error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> waitForInitialization({
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#waitForInitialization, [], {#timeout: timeout}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
